server.port: 8086
spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/awesome-chat?serverTimezone=UTC
    username: awesome-chat
    password: awesome-chat